In [2]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.ensemble import RandomForestClassifier

In [18]:
iris= load_iris()

In [19]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [20]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [21]:
x,y= load_iris(return_X_y=True)

In [22]:
from sklearn.model_selection import train_test_split

In [23]:
xtrain, xtest, ytrain, ytest= train_test_split(x, y, test_size= .30)

In [25]:
df= pd.DataFrame({'sepal length (cm)': iris.data[:,0], 'sepal width (cm)': iris.data[:,1],
                  'petal length (cm)': iris.data[:,2],  'petal width (cm)': iris.data[:,3],
                 'Target': iris.target})

In [26]:
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     Target  
0         0  
1         0  
2         0  
3         0  
4         0  
..      ...  
145       2  
146       2  
147       2  
148       2  
149       2  

[150 rows x 5 columns]

In [27]:
rfc= RandomForestClassifier(n_estimators=100)

In [33]:
print(xtrain.shape,
xtest.shape,
ytrain.shape,
ytest.shape)


(105, 4) (45, 4) (105,) (45,)


In [34]:
rfc.fit(xtrain, ytrain)

RandomForestClassifier()

In [35]:
ypred= rfc.predict(xtest)

In [38]:
ytest, ypred

(array([1, 2, 0, 1, 0, 2, 0, 1, 0, 1, 1, 0, 0, 0, 2, 2, 0, 1, 2, 2, 0, 2,
        1, 1, 1, 2, 1, 2, 1, 2, 0, 1, 1, 1, 0, 2, 2, 0, 2, 0, 1, 1, 0, 0,
        2]),
 array([1, 2, 0, 1, 0, 2, 0, 1, 0, 1, 1, 0, 0, 0, 2, 2, 0, 1, 2, 2, 0, 2,
        1, 1, 1, 2, 1, 2, 1, 1, 0, 1, 1, 1, 0, 2, 2, 0, 2, 0, 1, 1, 0, 0,
        2]))

In [43]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
print(accuracy_score(ytest, ypred))

0.9777777777777777


In [44]:
print(classification_report(ytest, ypred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        15
           1       0.94      1.00      0.97        16
           2       1.00      0.93      0.96        14

    accuracy                           0.98        45
   macro avg       0.98      0.98      0.98        45
weighted avg       0.98      0.98      0.98        45



In [45]:
print(confusion_matrix(ytest, ypred))

[[15  0  0]
 [ 0 16  0]
 [ 0  1 13]]


In [48]:
rfc.predict([[3,3,3,2]])

array([2])

In [57]:
pd.Series(rfc.feature_importances_, index = iris.feature_names)

sepal length (cm)    0.109133
sepal width (cm)     0.029241
petal length (cm)    0.465057
petal width (cm)     0.396570
dtype: float64

# Voting Classifier

In [59]:
from sklearn.ensemble import VotingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier

In [60]:
xtrain, xtest, ytrain, ytest= train_test_split(x, y, test_size= .20, random_state=42)

In [82]:
estimator=[]
estimator.append(('LR', LogisticRegression(max_iter=200,
    multi_class='multinomial')))
estimator.append(('SVC', SVC(gamma= 'auto', probability= True)))
estimator.append(('dtc', DecisionTreeClassifier()))


In [83]:
voth= VotingClassifier(estimators= estimator)

In [84]:
voth.fit(xtrain, ytrain)

VotingClassifier(estimators=[('LR',
                              LogisticRegression(max_iter=200,
                                                 multi_class='multinomial')),
                             ('SVC', SVC(gamma='auto', probability=True)),
                             ('dtc', DecisionTreeClassifier())])

In [85]:
votp=voth.predict(xtest)

In [86]:
print(accuracy_score(ytest, votp))

1.0


In [87]:
vots= VotingClassifier(estimators= estimator, voting='soft')
vots.fit(xtrain, ytrain)


VotingClassifier(estimators=[('LR',
                              LogisticRegression(max_iter=200,
                                                 multi_class='multinomial')),
                             ('SVC', SVC(gamma='auto', probability=True)),
                             ('dtc', DecisionTreeClassifier())],
                 voting='soft')

In [88]:
votsp= vots.predict(xtest)

In [89]:
accuracy_score(ytest, votsp)

1.0

# Bagging Classifier